### ISSUE TITLE
マスターから測定対象をHTTPSで取得する際にハングアップすることがある

### ISSUE THREAD

**Issue by moratori** [moratori/dnsprobe#41]
```
$ tailf -n15 logs/main_measurer.log
2019-11-03 11:57:02,664 [INFO] __main__ __load_measurement_info controller: https://<masked>
2019-11-03 11:57:12,527 [INFO] __main__ __load_measurement_info http status code: 200
2019-11-03 11:57:12,529 [INFO] __main__ __load_measurement_info json object load in properly from controller
2019-11-03 11:57:12,539 [INFO] __main__ start starting main routine
2019-11-03 11:57:15,048 [WARNING] __main__ __measurement_core timeout while measurement: The DNS operation timed out.
2019-11-03 11:57:20,513 [WARNING] __main__ __measurement_core timeout while measurement: The DNS operation timed out.
2019-11-03 11:57:24,792 [INFO] __main__ measure_toplevel 30 data measured
2019-11-03 11:57:24,882 [INFO] common.data.dao write_measurement_data writing data to influxdb
2019-11-03 11:58:03,293 [INFO] __main__ __set_global_ipaddress selected ipv4 address: <masked>
2019-11-03 11:58:03,293 [INFO] __main__ __set_global_ipaddress selected ipv6 address: <masked>
2019-11-03 11:58:03,294 [INFO] __main__ __set_net_description IPv4 description: <masked>
2019-11-03 11:58:03,294 [INFO] __main__ __set_net_description IPv6 description: <masked>
2019-11-03 11:58:03,294 [INFO] __main__ __load_measurement_info controller: https://<masked>

$ cat /proc/24905/wchan
sk_wait_data

$ gstack 24905
#0  0x00007efda8be36e0 in __read_nocancel () from /lib64/libpthread.so.0
#1  0x00007efd9f52483b in sock_read () from /lib64/libcrypto.so.10
#2  0x00007efd9f52287b in BIO_read () from /lib64/libcrypto.so.10
#3  0x00007efd9f894334 in ssl3_read_n () from /lib64/libssl.so.10
#4  0x00007efd9f895cf0 in ssl3_read_bytes () from /lib64/libssl.so.10
#5  0x00007efd9f892644 in ssl3_read_internal () from /lib64/libssl.so.10
#6  0x00007efd9c72e50c in _ssl__SSLSocket_read_impl ........
```

**Comment by moratori** [comment]
https://requests.kennethreitz.org/en/master/user/quickstart/#timeouts

**Comment by moratori** [comment]
トップレベルシェルでのtimeoutはいれている
